[tool.poetry]
name = "aula-python"
version = "0.1.0"
description = ""
authors = ["Diego Felipe <fdiego039@gmail.com>"]
readme = "README.md"
packages = [{ include = "src" }]  # ou ajuste conforme seu diretório principal

[tool.poetry.dependencies]
python = "^3.12"
flask = "*"
flask-sqlalchemy = "*"
flask-migrate = "*"
flask-jwt-extended = "*"
pytest = "*"
pytest-mock = "*"
psycopg2-binary = "*"
gunicorn = "*"

[tool.pytest.ini_options]
addopts = "-vvv"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"